from django.urls import path

from . import api


urlpatterns = [
    path("health/", api.health),
    path("analytics/dashboard/", api.analytics_dashboard),
    path("analytics/reports/live/", api.analytics_reports_live),
    path("analytics/reports/", api.analytics_dashboard),
    path("analytics/dashboard-summary/", api.analytics_summary),
    path("analytics/kpis/", api.analytics_kpis),
    path("analytics/stock-alerts/", api.analytics_stock_alerts),
    path("invoice-costs/repair/", api.repair_invoice_costs),
    path("system/health/", api.system_health),
    path("system/network/", api.system_network),
    path("system/readiness/", api.system_readiness),
    path("session/", api.session_status),
    path("auth/login/", api.auth_login),
    path("auth/logout/", api.auth_logout),
    path("setup/admin/", api.setup_admin),
    path("users/", api.users),
    path("users/<int:user_id>/", api.user_detail),
    path("users/<int:user_id>/payroll/", api.user_payroll),
    path("login-events/", api.login_events),
    path("state/", api.state_snapshot),
    path("sync/", api.sync_snapshot),
    path("system/reset/", api.system_reset),
    path("profit/", api.profit_snapshot),
    path("backup/", api.backup_export),
    path("backup/full/", api.backup_full_export),
    path("backup/full/verify/", api.backup_full_verify),
    path("backup/full/restore/", api.backup_full_restore),
    path("backup/verify/", api.backup_verify),
    path("backup/restore/", api.backup_restore),
    path("dashboard-review/", api.dashboard_review),
    path("audit/", api.audit_logs),
    path("customers/", api.customers),
    path("customers/<str:external_id>/", api.customer_detail),
    path("invoices/", api.invoices),
    path("invoices/<str:external_id>/", api.invoice_detail),
    path("purchases-ledger/", api.purchases),
    path("purchases-ledger/<str:external_id>/", api.purchase_detail),
    path("returns/", api.returns),
    path("returns/<str:external_id>/", api.return_detail),
    path("payments/", api.payments),
    path("installments/", api.installments),
    path("statements/", api.statements),
    path("stock/adjust/", api.stock_adjust),
    path("warehouses/", api.warehouses),
    path("warehouses/<str:external_id>/", api.warehouse_detail),
    path("pos/products/", api.pos_products),
    path("pos/products/<str:product_id>/", api.pos_product_detail),
    path("products/", api.products),
    path("products/<str:external_id>/", api.product_detail),
    path("products/<str:product_id>/images/", api.product_images),
    path("products/<str:product_id>/images/<str:image_id>/", api.product_image_detail),
    path("products/<str:product_id>/units/<str:unit_id>/", api.product_unit_detail),
    path("clients/", api.clients),
    path("clients/<str:external_id>/", api.client_detail),
    path("suppliers/", api.suppliers),
    path("suppliers/<str:external_id>/", api.supplier_detail),
    path("employees/", api.employees),
    path("employees/<str:external_id>/", api.employee_detail),
    
    path("super-admin/stats/", api.super_admin_stats),
    path("super-admin/users/", api.super_admin_users),
    path("super-admin/users/<int:user_id>/", api.super_admin_user_action),
]
