# Generated by Codex for TOX ERP backend bootstrap.
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=180)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("debt_limit_usd", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("loyalty_points", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=180)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("salary", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("work_hours", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=180)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(blank=True, max_length=60)),
                ("zone", models.CharField(blank=True, max_length=160)),
                ("manager", models.CharField(blank=True, max_length=160)),
                ("note", models.TextField(blank=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=220)),
                ("kind", models.CharField(choices=[("single", "Single"), ("packaged", "Packaged"), ("weighted", "Weighted"), ("liquid", "Liquid"), ("length", "Length")], default="single", max_length=30)),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=120)),
                ("sku", models.CharField(blank=True, max_length=120)),
                ("currency", models.CharField(default="IQD", max_length=8)),
                ("base_unit", models.CharField(default="قطعة", max_length=80)),
                ("stock_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("alert_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("expiry_start", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="erp.warehouse")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("multiplier", models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ("price_usd", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("price_currency", models.CharField(default="IQD", max_length=8)),
                ("barcode", models.CharField(blank=True, max_length=120)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="erp.product")),
            ],
            options={"ordering": ["id"], "abstract": False, "unique_together": {("product", "external_id")}},
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("movement_type", models.CharField(choices=[("sale", "Sale"), ("purchase", "Purchase"), ("adjustment", "Adjustment"), ("transfer", "Transfer"), ("archive", "Archive")], max_length=30)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="erp.product")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="erp.warehouse")),
            ],
        ),
    ]
