# Generated by Django 4.2 on 2026-05-09 12:52

from django.db import migrations, models
from django.db.models import Count


def clear_duplicate_unit_barcodes(apps, schema_editor):
    ProductUnit = apps.get_model("erp", "ProductUnit")
    duplicate_barcodes = (
        ProductUnit.objects.exclude(barcode="")
        .values("barcode")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for item in duplicate_barcodes:
        unit_ids = list(
            ProductUnit.objects.filter(barcode=item["barcode"])
            .order_by("id")
            .values_list("id", flat=True)
        )
        ProductUnit.objects.filter(id__in=unit_ids[1:]).update(barcode="")


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_product_storage_unit_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="alert_quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_unit_multiplier",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="multiplier",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.RunPython(clear_duplicate_unit_barcodes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="unique_non_empty_product_unit_barcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.CheckConstraint(
                check=models.Q(("multiplier__gt", 0)),
                name="product_unit_multiplier_positive",
            ),
        ),
    ]
