# Generated by Django 4.2 on 2026-05-09 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_alter_product_alert_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_currency", models.CharField(default="USD", max_length=8)),
                ("quote_currency", models.CharField(default="IQD", max_length=8)),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1460, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("salary", "Salary"),
                            ("utilities", "Utilities"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="IQD", max_length=8)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1460, max_digits=14),
                ),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="client",
            name="balance_iqd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="client",
            name="balance_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="supplier",
            name="balance_iqd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="supplier",
            name="balance_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_code", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "purchase_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="erp.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="erp.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "received_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["product", "warehouse", "expiry_date"],
                name="erp_stockba_product_f38e63_idx",
            ),
        ),
    ]
