# Generated by Django 4.2 on 2026-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0006_currencyrate_expense_client_balance_iqd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="alert_quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_unit_multiplier",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="multiplier",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
