# Generated by Django 4.2 on 2026-05-10 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_product_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.CharField(blank=True, max_length=80)),
                ("message", models.CharField(blank=True, max_length=240)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("customer_name", models.CharField(blank=True, max_length=180)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1460, max_digits=14),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "discount_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "paid_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="erp.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("supplier_name", models.CharField(blank=True, max_length=180)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1460, max_digits=14),
                ),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "paid_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="erp.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("supplier_name", models.CharField(blank=True, max_length=180)),
                (
                    "amount_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "unapplied_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("applied_to", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True)),
                ("paid_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="erp.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.CharField(blank=True, max_length=80)),
                ("unit_name", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "qty_in_base",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "unit_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("expiry_days", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_items",
                        to="erp.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="erp.purchase",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_items",
                        to="erp.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.CharField(blank=True, max_length=80)),
                ("unit_name", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "qty_in_base",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="erp.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="erp.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="erp.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                ("client_name", models.CharField(blank=True, max_length=180)),
                (
                    "amount_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "unapplied_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("note", models.TextField(blank=True)),
                ("received_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="erp.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
