# Generated by Django 4.2 on 2026-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_userprofile_loginevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpayment",
            name="applied_to",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="invoice",
            name="installment_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
