# Generated by Django 4.2 on 2026-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0012_userprofile_permissions_default_admin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="erp_auditlo_entity__a5fffd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="erp_auditlo_action_ad0111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["deleted_at", "name"], name="erp_client_deleted_de55c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["phone"], name="erp_client_phone_025683_idx"),
        ),
        migrations.AddIndex(
            model_name="clientpayment",
            index=models.Index(
                fields=["client", "created_at"], name="erp_clientp_client__55d5ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientpayment",
            index=models.Index(
                fields=["external_id"], name="erp_clientp_externa_7af2c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["deleted_at", "name"], name="erp_employe_deleted_bb8684_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["role"], name="erp_employe_role_6ba02c_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["deleted_at", "paid_at"], name="erp_expense_deleted_52fcdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="erp_expense_categor_7f710c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["created_at", "id"], name="erp_invoice_created_81a5c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "created_at"], name="erp_invoice_client__d308f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["external_id"], name="erp_invoice_externa_f977df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["invoice", "product"], name="erp_invoice_invoice_90fa98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["product", "warehouse"], name="erp_invoice_product_4899e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["warehouse", "deleted_at"],
                name="erp_product_warehou_e153a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="erp_product_name_153a90_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="erp_product_sku_8f234c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["expires_at"], name="erp_product_expires_4851c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["created_at", "id"], name="erp_purchas_created_703c1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier", "created_at"], name="erp_purchas_supplie_c4f332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["external_id"], name="erp_purchas_externa_b79e9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["purchase", "product"], name="erp_purchas_purchas_4dda18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["product", "warehouse"], name="erp_purchas_product_59b7cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["expires_at"], name="erp_purchas_expires_08ba97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "warehouse", "created_at"],
                name="erp_stockmo_product_554b79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"],
                name="erp_stockmo_movemen_7eac12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["deleted_at", "name"], name="erp_supplie_deleted_e2ab83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["phone"], name="erp_supplie_phone_a6899a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["supplier", "created_at"], name="erp_supplie_supplie_b6ea91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["external_id"], name="erp_supplie_externa_0c5d36_idx"
            ),
        ),
    ]
