# Generated by Codex on 2026-05-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0013_auditlog_erp_auditlo_entity__a5fffd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="financial_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="opening_balance_type",
            field=models.CharField(default="debit", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="opening_balance_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="supplier",
            name="financial_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="opening_balance_type",
            field=models.CharField(default="debit", max_length=20),
        ),
        migrations.AddField(
            model_name="supplier",
            name="opening_balance_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(default="unpaid", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="remaining_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="purchase",
            name="payment_status",
            field=models.CharField(default="unpaid", max_length=20),
        ),
        migrations.AddField(
            model_name="purchase",
            name="remaining_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name="AccountMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=120, unique=True)),
                ("party_type", models.CharField(choices=[("client", "Client"), ("supplier", "Supplier")], max_length=20)),
                ("party_id", models.CharField(db_index=True, max_length=80)),
                ("movement_type", models.CharField(choices=[("opening", "Opening balance"), ("invoice", "Invoice"), ("payment", "Payment"), ("return", "Return"), ("adjustment", "Adjustment")], max_length=24)),
                ("title", models.CharField(max_length=160)),
                ("debit_usd", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("credit_usd", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("balance_after_usd", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("reference_type", models.CharField(blank=True, max_length=40)),
                ("reference_id", models.CharField(blank=True, max_length=80)),
                ("note", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["party_type", "party_id", "created_at"], name="erp_account_party_t_3ad73a_idx"),
                    models.Index(fields=["movement_type", "created_at"], name="erp_account_movemen_37a8a6_idx"),
                    models.Index(fields=["reference_type", "reference_id"], name="erp_account_referen_abeb36_idx"),
                ],
            },
        ),
    ]
