# Generated by Django 4.2 on 2026-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0014_account_ledger_2026"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "payment_status", "created_at"],
                name="erp_invoice_client__aa92eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier", "payment_status", "created_at"],
                name="erp_purchas_supplie_79d11a_idx",
            ),
        ),
    ]
