# Generated by Django 4.2 on 2026-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0015_performance_indexes_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
