# Generated by Django 4.2 on 2026-05-12 21:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _money(value):
    try:
        return Decimal(str(value if value not in (None, "") else "0")).quantize(Decimal("0.0001"))
    except Exception:
        return Decimal("0.0000")


def _opening_signed_usd(amount, balance_type):
    value = abs(_money(amount))
    if value <= 0:
        return Decimal("0.0000")
    return -value if (balance_type or "debit") in {"credit", "advance"} else value


def _ledger_defaults(entity_type, entity, amount, reference_model, timestamp, metadata=None, **relations):
    defaults = {
        "entity_id": entity.external_id,
        "amount_usd": _money(amount),
        "reference_model": reference_model,
        "metadata": metadata or {},
        "timestamp": timestamp or django.utils.timezone.now(),
        "customer_id": None,
        "supplier_id": None,
        "invoice_id": relations.get("invoice_id"),
        "purchase_id": relations.get("purchase_id"),
        "payment_id": relations.get("payment_id"),
        "supplier_payment_id": relations.get("supplier_payment_id"),
        "installment_id": relations.get("installment_id"),
    }
    if entity_type == "customer":
        defaults["customer_id"] = entity.id
    else:
        defaults["supplier_id"] = entity.id
    return defaults


def _create_ledger(LedgerEntry, entity_type, entity, amount, entry_type, reference_id, reference_model, timestamp=None, metadata=None, **relations):
    amount = _money(amount)
    if amount == 0 or not entity or not reference_id:
        return None
    LedgerEntry.objects.get_or_create(
        entity_type=entity_type,
        entity_id=entity.external_id,
        type=entry_type,
        reference_id=reference_id,
        defaults=_ledger_defaults(
            entity_type,
            entity,
            amount,
            reference_model,
            timestamp,
            metadata=metadata,
            **relations,
        ),
    )


def backfill_financial_ledger(apps, schema_editor):
    Client = apps.get_model("erp", "Client")
    ClientPayment = apps.get_model("erp", "ClientPayment")
    Installment = apps.get_model("erp", "Installment")
    Invoice = apps.get_model("erp", "Invoice")
    LedgerEntry = apps.get_model("erp", "LedgerEntry")
    Purchase = apps.get_model("erp", "Purchase")
    Supplier = apps.get_model("erp", "Supplier")
    SupplierPayment = apps.get_model("erp", "SupplierPayment")

    for client in Client.objects.all():
        amount = _opening_signed_usd(client.opening_balance_usd, client.opening_balance_type)
        _create_ledger(
            LedgerEntry,
            "customer",
            client,
            amount,
            "DEBT_ADJUSTMENT",
            f"customer-opening-{client.external_id}",
            "customer",
            timestamp=client.created_at,
            metadata={"openingBalanceType": client.opening_balance_type, "note": client.financial_note},
        )

    for supplier in Supplier.objects.all():
        amount = _opening_signed_usd(supplier.opening_balance_usd, supplier.opening_balance_type)
        _create_ledger(
            LedgerEntry,
            "supplier",
            supplier,
            amount,
            "DEBT_ADJUSTMENT",
            f"supplier-opening-{supplier.external_id}",
            "supplier",
            timestamp=supplier.created_at,
            metadata={"openingBalanceType": supplier.opening_balance_type, "note": supplier.financial_note},
        )

    for invoice in Invoice.objects.select_related("client").all():
        if not invoice.client_id:
            continue
        plan = invoice.installment_plan if isinstance(invoice.installment_plan, dict) else {}
        schedule = plan.get("schedule") if isinstance(plan.get("schedule"), list) else []
        for index, item in enumerate(schedule):
            try:
                number = int(item.get("number") or index + 1)
            except Exception:
                number = index + 1
            Installment.objects.get_or_create(
                invoice_id=invoice.id,
                number=number,
                defaults={
                    "external_id": item.get("id") or item.get("installmentId") or f"{invoice.external_id}-INS-{number}",
                    "client_id": invoice.client_id,
                    "amount_usd": _money(item.get("amountUsd")),
                    "due_date": item.get("dueDate") or None,
                    "created_at": invoice.created_at,
                },
            )
        _create_ledger(
            LedgerEntry,
            "customer",
            invoice.client,
            invoice.total_usd,
            "INVOICE_CREATED",
            invoice.external_id,
            "invoice",
            timestamp=invoice.created_at,
            metadata={"paymentStatus": invoice.payment_status},
            invoice_id=invoice.id,
        )
        applied = Decimal("0.0000")
        for payment in ClientPayment.objects.filter(client_id=invoice.client_id):
            for item in payment.applied_to or []:
                if item.get("invoiceId") == invoice.external_id:
                    applied += _money(item.get("amountUsd"))
        immediate_paid = max(Decimal("0.0000"), _money(invoice.paid_usd - applied))
        _create_ledger(
            LedgerEntry,
            "customer",
            invoice.client,
            -immediate_paid,
            "PAYMENT_RECEIVED",
            f"invoice-paid-{invoice.external_id}",
            "invoice_payment",
            timestamp=invoice.created_at,
            metadata={"invoiceId": invoice.external_id, "source": "invoice.paid_usd"},
            invoice_id=invoice.id,
        )

    for purchase in Purchase.objects.select_related("supplier").all():
        if not purchase.supplier_id:
            continue
        _create_ledger(
            LedgerEntry,
            "supplier",
            purchase.supplier,
            purchase.cost_usd,
            "INVOICE_CREATED",
            purchase.external_id,
            "purchase",
            timestamp=purchase.created_at,
            metadata={"paymentStatus": purchase.payment_status},
            purchase_id=purchase.id,
        )
        applied = Decimal("0.0000")
        for payment in SupplierPayment.objects.filter(supplier_id=purchase.supplier_id):
            for item in payment.applied_to or []:
                if item.get("purchaseId") == purchase.external_id:
                    applied += _money(item.get("amountUsd"))
        immediate_paid = max(Decimal("0.0000"), _money(purchase.paid_usd - applied))
        _create_ledger(
            LedgerEntry,
            "supplier",
            purchase.supplier,
            -immediate_paid,
            "PAYMENT_RECEIVED",
            f"purchase-paid-{purchase.external_id}",
            "purchase_payment",
            timestamp=purchase.created_at,
            metadata={"purchaseId": purchase.external_id, "source": "purchase.paid_usd"},
            purchase_id=purchase.id,
        )

    for payment in ClientPayment.objects.select_related("client").all():
        if not payment.client_id:
            continue
        installment = None
        for item in payment.applied_to or []:
            if item.get("installmentId"):
                installment = Installment.objects.filter(external_id=item.get("installmentId")).first()
            elif item.get("invoiceId") and item.get("installmentNumber"):
                installment = Installment.objects.filter(
                    invoice__external_id=item.get("invoiceId"),
                    number=item.get("installmentNumber"),
                ).first()
            if installment:
                break
        entry_type = "INSTALLMENT_PAYMENT" if installment else "PAYMENT_RECEIVED"
        _create_ledger(
            LedgerEntry,
            "customer",
            payment.client,
            -payment.amount_usd,
            entry_type,
            payment.external_id,
            "payment",
            timestamp=payment.created_at,
            metadata={"appliedTo": payment.applied_to, "unappliedUsd": float(payment.unapplied_usd)},
            payment_id=payment.id,
            installment_id=installment.id if installment else None,
        )

    for payment in SupplierPayment.objects.select_related("supplier").all():
        if not payment.supplier_id:
            continue
        _create_ledger(
            LedgerEntry,
            "supplier",
            payment.supplier,
            -payment.amount_usd,
            "PAYMENT_RECEIVED",
            payment.external_id,
            "supplier_payment",
            timestamp=payment.created_at,
            metadata={"appliedTo": payment.applied_to, "unappliedUsd": float(payment.unapplied_usd)},
            supplier_payment_id=payment.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0016_client_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("number", models.PositiveIntegerField()),
                ("amount_usd", models.DecimalField(decimal_places=4, max_digits=14)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["due_date", "number", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="balance_iqd",
        ),
        migrations.RemoveField(
            model_name="client",
            name="balance_usd",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="balance_iqd",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="balance_usd",
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("customer", "Customer"), ("supplier", "Supplier")],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=80)),
                ("amount_usd", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INVOICE_CREATED", "Invoice created"),
                            ("PAYMENT_RECEIVED", "Payment received"),
                            ("INSTALLMENT_PAYMENT", "Installment payment"),
                            ("DEBT_ADJUSTMENT", "Debt adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reference_id", models.CharField(db_index=True, max_length=120)),
                ("reference_model", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.client",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.installment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.clientpayment",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.purchase",
                    ),
                ),
                (
                    "reversed_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_entries",
                        to="erp.ledgerentry",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.supplier",
                    ),
                ),
                (
                    "supplier_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="erp.supplierpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.AddField(
            model_name="installment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installments",
                to="erp.client",
            ),
        ),
        migrations.AddField(
            model_name="installment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installments",
                to="erp.invoice",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["entity_type", "entity_id", "timestamp"],
                name="erp_ledgere_entity__27d826_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["type", "timestamp"], name="erp_ledgere_type_402e69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["reference_model", "reference_id"],
                name="erp_ledgere_referen_affc50_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_usd", 0), _negated=True),
                name="ledger_entry_amount_non_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("entity_type", "customer"),
                        ("supplier__isnull", True),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("entity_type", "supplier"),
                        ("supplier__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ledger_entry_exact_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "entity_id", "type", "reference_id"),
                name="unique_ledger_entry_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(
                fields=["client", "due_date"], name="erp_install_client__6858c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(
                fields=["invoice", "number"], name="erp_install_invoice_fd3c43_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="installment",
            unique_together={("invoice", "number")},
        ),
        migrations.RunPython(backfill_financial_ledger, migrations.RunPython.noop),
    ]
