# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0018_client_image_employee_user_supplier_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="void_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="void_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
