# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0019_product_image_invoice_purchase_void"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="title",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="purchase",
            name="title",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
