# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0020_invoice_purchase_titles_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("direct_pos", "Direct POS"),
                    ("installment", "Installment"),
                ],
                default="invoice",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["kind", "created_at"], name="erp_invoice_kind_created_idx"),
        ),
    ]
