# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0021_invoice_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="color",
            field=models.CharField(default="#d6b35a", max_length=24),
        ),
    ]
