# Generated by Django 4.2.7 on 2026-06-07 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import erp.models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0026_purchase_landed_cost_batches"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                (
                    "original",
                    models.FileField(
                        blank=True, upload_to=erp.models.product_image_upload_to
                    ),
                ),
                (
                    "large",
                    models.FileField(
                        blank=True, upload_to=erp.models.product_image_upload_to
                    ),
                ),
                (
                    "catalog",
                    models.FileField(
                        blank=True, upload_to=erp.models.product_image_upload_to
                    ),
                ),
                (
                    "thumb",
                    models.FileField(
                        blank=True, upload_to=erp.models.product_image_upload_to
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="erp.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "sort_order"],
                        name="erp_product_image_order_idx",
                    ),
                    models.Index(
                        fields=["product", "is_primary"],
                        name="erp_product_image_primary_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="unique_primary_product_image",
            ),
        ),
    ]
