# Generated by Django 5.2.16 on 2026-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0030_return_documents"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="returndocument",
            new_name="erp_returnd_return__6f91c6_idx",
            old_name="erp_returnd_return__9d4f77_idx",
        ),
        migrations.RenameIndex(
            model_name="returndocument",
            new_name="erp_returnd_invoice_af4c90_idx",
            old_name="erp_returnd_invoice_27b9f8_idx",
        ),
        migrations.RenameIndex(
            model_name="returndocument",
            new_name="erp_returnd_purchas_3cc6ec_idx",
            old_name="erp_returnd_purchase_59d8b1_idx",
        ),
        migrations.RenameIndex(
            model_name="returndocument",
            new_name="erp_returnd_client__fd3cbd_idx",
            old_name="erp_returnd_client__57c1f1_idx",
        ),
        migrations.RenameIndex(
            model_name="returndocument",
            new_name="erp_returnd_supplie_06760f_idx",
            old_name="erp_returnd_supplier_6f94c3_idx",
        ),
        migrations.RenameIndex(
            model_name="returnitem",
            new_name="erp_returni_return__5a6f03_idx",
            old_name="erp_returni_return__940653_idx",
        ),
        migrations.RenameIndex(
            model_name="returnitem",
            new_name="erp_returni_invoice_d9a778_idx",
            old_name="erp_returni_invoice_2b6624_idx",
        ),
        migrations.RenameIndex(
            model_name="returnitem",
            new_name="erp_returni_purchas_15ffce_idx",
            old_name="erp_returni_purchase_097a78_idx",
        ),
        migrations.RenameIndex(
            model_name="returnitem",
            new_name="erp_returni_product_c802cb_idx",
            old_name="erp_returni_product_4fb12f_idx",
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("purchase", "Purchase"),
                    ("sale_return", "Sale return"),
                    ("purchase_return", "Purchase return"),
                    ("return_damage", "Return damage"),
                    ("adjustment", "Adjustment"),
                    ("transfer", "Transfer"),
                    ("archive", "Archive"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("cashier", "Cashier"),
                    ("warehouse", "Warehouse"),
                    ("accountant", "Accountant"),
                ],
                default="cashier",
                max_length=30,
            ),
        ),
    ]
