# Generated by Django 5.2.16 on 2026-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erp",
            "0031_rename_erp_returnd_return__9d4f77_idx_erp_returnd_return__6f91c6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
