# Generated by Django 5.2.16 on 2026-08-18 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_legacy_account_owners(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("erp", "UserProfile")
    super_admin = User.objects.filter(username="super_admin").first()
    fallback_manager = User.objects.filter(is_superuser=True).exclude(username="super_admin").order_by("id").first()
    for profile in UserProfile.objects.select_related("user").all():
        if profile.role == "super_admin":
            continue
        if profile.role == "admin":
            profile.managed_by_id = super_admin.id if super_admin else None
        else:
            manager = fallback_manager or super_admin
            profile.managed_by_id = manager.id if manager else None
        profile.save(update_fields=["managed_by"])


def unassign_legacy_account_owners(apps, schema_editor):
    UserProfile = apps.get_model("erp", "UserProfile")
    UserProfile.objects.update(managed_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0032_userprofile_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The manager or tenant owner responsible for this account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_tox_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_legacy_account_owners, unassign_legacy_account_owners),
    ]
